name = "Strata"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/alexnorell/strata/blob/master/LICENSE.md"
description = "A responsive and minimal single-page portfolio with blogging capabilities."
homepage = "//github.com/alexnorell/strata"
tags = ["image gallery", "contact form", "google analytics", "customizable", "blog", "single-page"]
features = ["", ""]
min_version = 0.60

[author]
  name = "Alex Norell"
  homepage = "//github.com/alexnorell"

# If porting an existing theme
[original]
  name = "AJ"
  homepage = "//html5up.net/"
[port]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
